### ISSUE TITLE
Question: does gsort use $TMPDIR?

### ISSUE THREAD

**Issue by davemcg** [brentp/gsort#3]
I've trying to optimize gsort for an extremely large vcf (168gb) and I'm wondering what gsort uses as the tmpdir.

From scanning the source, I see it uses `os.TempDir()` on line 298 for the matches. This is $TMPDIR for a linux-based system?

I have access to an extremely large memory node (up to 800gb), but from scanning the readme it looks like gsort will write the file to the $TMPDIR even if the whole operation fits in memory? 

If that's the case, then I want to make sure gsort is using the fastest drive for the $TMPDIR write.

**Comment by brentp** [comment]
yes, it will respect $TMPDIR.
